API/BUG: Use lists instead of ndarrays
If using ndarrays you could compromise compatibility in some versions of
numpy where comparing arrays of strings is not supported and you would
get a traceback for doing something like this:

>>> import numpy as np
>>> a = np.array(['yo', 'samples', "it's"], dtype='str')
>>> b = np.array(['yo', "it's", 'samples'], dtype='str')
>>> np.array_equal(a, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yova1074/qiime_software/numpy-1.7.1-release/lib/python2.7/site-packages/numpy/core/numeric.py", line 2119, in array_equal
    return bool(equal(a1,a2).all())
AttributeError: 'NotImplementedType' object has no attribute 'all'

Note that this is happening in 1.7.1 (I was only able to reproduce this
problem in a RHEL installation.